# Generated by Django 5.0.6 on 2024-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_alter_reciperequirement_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
